version: '3.3' #Specifying compose version

#Creating database and wordpress services
services:
   db:
     image: mysql:8.0
     volumes:
       - db_data:/var/lib/mysql
     restart: always
     env_file: .env #This file should have database credentials specified
     environment:
       MYSQL_DATABASE: wordpress
     command: '--default-authentication-plugin=mysql_native_password'


   wordpress:
     depends_on:
       - db
     image: wordpress:latest
     ports:
       - "8081:80"
     restart: always
     env_file: .env
     volumes:
       - wp_data:/var/www/html/wp-content
     environment:
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_USER: $MYSQL_USER #Variables which are taken from the env file
       WORDPRESS_DB_PASSWORD: $MYSQL_PASSWORD
       WORDPRESS_DB_NAME: wordpress
volumes:
  wp_data: {}
  db_data: {}
